//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCal
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONSULTANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CONSULTANT()
        {
            this.T_CRA = new HashSet<T_CRA>();
        }
    
        public int ID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string CLIENT { get; set; }
        public string SOCIETE { get; set; }
        public string CONTRAT { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> PROJECT_ID { get; set; }
    
        public virtual T_CUSTOMER T_CUSTOMER { get; set; }
        public virtual T_PROJECT T_PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CRA> T_CRA { get; set; }
    }
}
