//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCal
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CRA
    {
        public int ID { get; set; }
        public string MOIS { get; set; }
        public string ANNEE { get; set; }
        public Nullable<int> RESSOURCE { get; set; }
        public string JOUR { get; set; }
        public Nullable<int> JOURINFO { get; set; }
        public Nullable<long> DATEMS { get; set; }
    
        public virtual T_CONSULTANT T_CONSULTANT { get; set; }
        public virtual T_TYPEJOUR T_TYPEJOUR { get; set; }
    }
}
