//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCal
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CUSTOMER()
        {
            this.T_CONSULTANT = new HashSet<T_CONSULTANT>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_CONTRACT { get; set; }
        public string CUSTOMER_CONTACT { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public int CUSTOMER_PROJECT_ID { get; set; }
        public Nullable<System.DateTime> CUSTOMER_CREATION { get; set; }
        public Nullable<System.DateTime> CUSTOMER_UPDATE { get; set; }
        public bool CUSTOMER_ACTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CONSULTANT> T_CONSULTANT { get; set; }
    }
}
